//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestBankingConsoleClient.AcountService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AcountService.IAccountService")]
    public interface IAccountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Balance", ReplyAction="http://tempuri.org/IAccountService/BalanceResponse")]
        RestBankingClient.RestBankingService.AccountResponse Balance(int accountNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Balance", ReplyAction="http://tempuri.org/IAccountService/BalanceResponse")]
        System.Threading.Tasks.Task<RestBankingClient.RestBankingService.AccountResponse> BalanceAsync(int accountNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Deposit", ReplyAction="http://tempuri.org/IAccountService/DepositResponse")]
        RestBankingClient.RestBankingService.AccountResponse Deposit(RestBankingClient.RestBankingService.AccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Deposit", ReplyAction="http://tempuri.org/IAccountService/DepositResponse")]
        System.Threading.Tasks.Task<RestBankingClient.RestBankingService.AccountResponse> DepositAsync(RestBankingClient.RestBankingService.AccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Withdraw", ReplyAction="http://tempuri.org/IAccountService/WithdrawResponse")]
        RestBankingClient.RestBankingService.AccountResponse Withdraw(RestBankingClient.RestBankingService.AccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Withdraw", ReplyAction="http://tempuri.org/IAccountService/WithdrawResponse")]
        System.Threading.Tasks.Task<RestBankingClient.RestBankingService.AccountResponse> WithdrawAsync(RestBankingClient.RestBankingService.AccountRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountServiceChannel : RestBankingConsoleClient.AcountService.IAccountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountServiceClient : System.ServiceModel.ClientBase<RestBankingConsoleClient.AcountService.IAccountService>, RestBankingConsoleClient.AcountService.IAccountService {
        
        public AccountServiceClient() {
        }
        
        public AccountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RestBankingClient.RestBankingService.AccountResponse Balance(int accountNumber) {
            return base.Channel.Balance(accountNumber);
        }
        
        public System.Threading.Tasks.Task<RestBankingClient.RestBankingService.AccountResponse> BalanceAsync(int accountNumber) {
            return base.Channel.BalanceAsync(accountNumber);
        }
        
        public RestBankingClient.RestBankingService.AccountResponse Deposit(RestBankingClient.RestBankingService.AccountRequest request) {
            return base.Channel.Deposit(request);
        }
        
        public System.Threading.Tasks.Task<RestBankingClient.RestBankingService.AccountResponse> DepositAsync(RestBankingClient.RestBankingService.AccountRequest request) {
            return base.Channel.DepositAsync(request);
        }
        
        public RestBankingClient.RestBankingService.AccountResponse Withdraw(RestBankingClient.RestBankingService.AccountRequest request) {
            return base.Channel.Withdraw(request);
        }
        
        public System.Threading.Tasks.Task<RestBankingClient.RestBankingService.AccountResponse> WithdrawAsync(RestBankingClient.RestBankingService.AccountRequest request) {
            return base.Channel.WithdrawAsync(request);
        }
    }
}
